const categories = [
  {
    slug: "badmoebel",
    title: "Badmöbel",
    subcategories: [
      { name: "Badmöbel Sets", slug: "badmoebel-sets" },
      { name: "Waschtische mit Unterschrank", slug: "waschtische" },
      { name: "Spiegelschränke", slug: "spiegelschraenke" },
      { name: "Badspiegel", slug: "badspiegel" },
      { name: "Badschränke", slug: "badschraenke" },
      { name: "Waschtischunterschränke", slug: "waschtischunterschraenke" },
      { name: "Einzelmöbel", slug: "einzelmoebel" },
      { name: "Gäste- & Kleinbäder", slug: "gaestebad" },
      { name: "Sale %", slug: "sale" },
    ],
  },
  {
    slug: "duschen",
    title: "Duschen",
    subcategories: [
      { name: "Duschkabinen", slug: "duschkabinen" },
      { name: "Duschwannen", slug: "duschwannen" },
      { name: "Duschrückwände", slug: "duschrueckwaende" },
      { name: "Duschsysteme", slug: "duschsysteme" },
      { name: "Duschpaneele", slug: "duschpaneele" },
      { name: "Brausen", slug: "brausen" },
      { name: "Duscharmaturen", slug: "duscharmaturen" },
      { name: "Gäste- & Kleinbäder", slug: "gaestebad" },
      { name: "Barrierefreie Duschen", slug: "barrierefrei" },
      { name: "Sale %", slug: "sale" },
    ],
  },
  {
    slug: "baden",
    title: "Baden",
    subcategories: [
      { name: "Badewannen", slug: "badewannen" },
      { name: "Whirlpools", slug: "whirlpools" },
      { name: "Badewannenaufsätze", slug: "badewannenaufsaetze" },
      { name: "Badewannenarmaturen", slug: "badewannenarmaturen" },
      { name: "Brausegarnituren", slug: "brausegarnituren" },
      { name: "Handbrausen", slug: "handbrausen" },
      { name: "Gäste- & Kleinbäder", slug: "gaestebad" },
      { name: "Barrierefreie Badewannen", slug: "barrierefrei" },
      { name: "Sale %", slug: "sale" },
    ],
  },
  {
    slug: "badheizkoerper",
    title: "Badheizkörper",
    subcategories: [
      { name: "Handtuchheizkörper", slug: "handtuchheizkoerper" },
      { name: "Elektroheizkörper", slug: "elektroheizkoerper" },
      { name: "Flächenheizkörper", slug: "flaechenheizkoerper" },
      { name: "Röhrenheizkörper", slug: "roehrensysteme" },
      { name: "Paneelheizkörper", slug: "paneelheizkoerper" },
      { name: "Infrarotheizkörper", slug: "infrarotheizkoerper" },
      { name: "Gäste- & Kleinbäder", slug: "gaestebad" },
    ],
  },
  {
    slug: "badkeramik",
    title: "Badkeramik",
    subcategories: [
      { name: "Waschtische & Waschbecken", slug: "waschtische" },
      { name: "Aufsatzwaschbecken", slug: "aufsatzwaschbecken" },
      { name: "Handwaschbecken", slug: "handwaschbecken" },
      { name: "WCs & Toiletten", slug: "toiletten" },
      { name: "Bidets", slug: "bidets" },
      { name: "Urinale", slug: "urinale" },
      { name: "Drückerplatten & Betätigungsplatten", slug: "drueckerplatten" },
      { name: "Spülkästen", slug: "spuelkaesten" },
      { name: "Ablauf- & Montagesysteme", slug: "montagesysteme" },
    ],
  },
  {
    slug: "badarmaturen",
    title: "Badarmaturen",
    subcategories: [
      { name: "Waschtischarmaturen", slug: "waschtischarmaturen" },
      { name: "Duscharmaturen", slug: "duscharmaturen" },
      { name: "Badewannenarmaturen", slug: "badewannenarmaturen" },
      { name: "Bidetarmaturen", slug: "bidetarmaturen" },
      { name: "Duschsysteme & -paneele", slug: "duschsysteme" },
      { name: "Brausen", slug: "brausen" },
      { name: "Häufig gesucht", slug: "haeufig-gesucht" },
    ],
  },
  {
    slug: "zubehoer",
    title: "Zubehör",
    subcategories: [
      { name: "Bad-Accessoires", slug: "bad-accessoires" },
      { name: "Bad-Zubehör", slug: "bad-zubehoer" },
      { name: "Bad-Accessoire Sets", slug: "accessoire-sets" },
      { name: "Handtuchhalter", slug: "handtuchhalter" },
      { name: "Kosmetikspiegel", slug: "kosmetikspiegel" },
      { name: "Barrierefreies Bad", slug: "barrierefrei" },
    ],
  },
];

export default categories;
